name: Oblique stories
favicon: null
layout_spectrum: 1
typography_spectrum: 0.3924731
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#F3FFFF'
    - '#0F111D'
    - '#F48DB3'
    - '#E1EE08'
    - '#B5435C'
  brandStrength: 0.875
  lightness: 0.2096774
  saturation: 0.5143369
  rhythmicContrast: 0.4283154
purpose: []
