layout_spectrum: 1
color:
  saturation: 0.5143369
  lightness: 0.2096774
  brandStrength: 1
  brandColors:
    - '#F3FFFF'
    - '#0F111D'
    - '#F48DB3'
    - '#E1EE08'
    - '#B5435C'
  rhythmicContrast: 0.4283154
typography_spectrum: 0.3924731
name: Oblique stories
